#!/usr/bin/python3

import turtle
import cmd

class Console(cmd.Cmd):
    prompt = '(cmd) '
    intro = 'Welcome to my Console'
    file = None
    """defines the class of the cmd console"""

    def do_say_hi(self, name):
        'prints a name'
        print(f"Hi {name}")

    def do_new(self, line):
        'opens a second terminal'
        prompt = '>cmd'
        intro = 'second terminal'

    def do_EOF(self, quit):
        'terminates the terminal'
        return True

if __name__ == "__main__":
    Console().cmdloop()

print("\nGenerated by Masino")
